### ISSUE TITLE
POT not generated in 13.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-promotion#12]
@sbidoul I'm not able to see why POT files of latest modules has not been generated through Travis. Can you please take a look?

**Comment by sbidoul** [comment]
The github token was not set in the travis configuration. It should be ok now.

**Comment by pedrobaeza** [comment]
Thanks! I always forget this one.

**Comment by pedrobaeza** [comment]
cc @CarlosRoca13

**Comment by sbidoul** [comment]
With GitHub actions it will be an org-level secret, so easier.

**Comment by pedrobaeza** [comment]
Great, we reduce the entry barrier for new repos. The copier template has been also a great one for this.
