### ISSUE TITLE
limit  of Maximum Customer Applications for a Promotion is not getting applied

### ISSUE THREAD

**Issue by mdfaisalpapa** [OCA/sale-promotion#150]
## Module
coupon_limit
## Describe the bug
Iam on Odoo 15 community edition. I have enabled Promotions for my POS and have installed  [Coupon Limit | Odoo Apps Store](https://apps%5C.odoo%5C.com/apps/modules/15%5C.0/coupon_limit/) app and set the Max. Customer Applications as below
![image](https://github.com/OCA/sale-promotion/assets/108850128/e5ce3cd9-963f-475a-a00a-6bd8dad1b49a)
The output expected is that the promotion should be applied to the customer only once but the promotion is getting applied multiple times for the customer. Kindly help

## To Reproduce
Odoo 15 Community Edition
1.Set the Max. Customer Applications to 1
2. Open POS and Add products worth more than the limit set
3. Promotion is getting applied more than the once

**Expected behavior**
The output expected is that the promotion should be applied to the customer only once but the promotion is getting applied multiple times for the customer.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
There's no extension for PoS for this module. That's why it's not working. It's only done for sales orders. Closing as no present feature.
