### ISSUE TITLE
Looks like coupon_domain_product_discount can not be used without sale_coupon_domain_product_discount

### ISSUE THREAD

**Issue by nivels-x1g1** [OCA/sale-promotion#169]
Looks like coupon_domain_product_discount can not be used without 

sale_coupon_domain_product_discount
```
"depends": ["sale_coupon", "coupon_domain_product_discount"],
```

but
coupon_domain_product_discount depends also from sale_coupon_domain_product_discount

```
coupon_domain_product_discount/models/coupon_program.py", line 25, in _filter_not_ordered_reward_programs
    domain = order._get_reward_values_discount_strict_limit_lines(program)
AttributeError: 'sale.order' object has no attribute '_get_reward_values_discount_strict_limit_lines'
````
## Module
coupon_domain_product_discount 
Version: 15.0.1.1.0

## Describe the bug
If Strict Per Product Limit was enabeld I get error above

## To Reproduce

1. create coupon program
2. set discount apply on to specific products
3. set discount apply on domain 
4. set strict per product limit

**Expected behavior**
no error
one module or definition of function also in coupon_domain_product_discount

**Comment by chienandalu** [comment]
please check @pilarvargas-tecnativa

**Comment by pilarvargas-tecnativa** [comment]
The issue is solved with the PR: https://github.com/OCA/sale-promotion/pull/172
