### ISSUE TITLE
[14.0] sale_coupon_auto_refresh error when deleting sale order line

### ISSUE THREAD

**Issue by remi-filament** [OCA/sale-promotion#20]
After installing sale_coupon_refresh, Promotions are properly applied automatically on sale orders.
However, if I change my mind and update the sale order to remove either promotion line or the sale order line at the origin of the promotion I get a 
MissingError : Missing Record
Record does not exist or has been deleted.

I have been trying to look where the problem stood but could not find the source of the issue...

**Comment by pedrobaeza** [comment]
See #19
