### ISSUE TITLE
Is this the right repository to add a module that mimic unit of sale (uos, uos_coef and _qty)  in sale order line ?

### ISSUE THREAD

**Issue by luffah** [OCA/sale-promotion#36]
Hello,

In order to upgrade Odoo from an old version, we need to have an equivalent (on input side) to unit of sale.
UoS was used to have a custom price for a pack of mutiple similar piece (e.g. to have 5 apples weighting 80 gram each in one sale.order.line).

To this end, we prepare a module that convert user input (_coef and _qty) to the standard field (uom_quantity).
Is is this the right repo to propose this module ?

**Comment by pedrobaeza** [comment]
No, it's not. It would be OCA/sale-workflow. But you should check `sale_order_secondary_unit` for a similar feature.
