### ISSUE TITLE
14.0 branch missing

### ISSUE THREAD

**Issue by SilvioC2C** [OCA/sale-promotion#7]
Hello everyone,
I was willing to migrate [this module](https://github.com/OCA/sale-promotion/tree/13.0/sale_coupon_order_line_link) from v13.0 to v14.0, but it seems there's no branch 14.0 yet.
Could someone create it, please?

**Comment by SilvioC2C** [comment]
CC @pedrobaeza

**Comment by pedrobaeza** [comment]
Created:

https://github.com/OCA/sale-promotion/tree/14.0
